### ISSUE TITLE
Composer remove 'Uncaught ReflectionException'

### ISSUE THREAD

**Issue by PixellUp** [GrahamCampbell/Laravel-Exceptions#103]
When you do folloing command `composer remove graham-campbell/exceptions` it throw following error and doesn't been removed it.

```
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
PHP Fatal error:  Uncaught ReflectionException: Class GrahamCampbell\Exceptions\NewExceptionHandler does not exist in D:\XAMPP\htdocs\test\vendor\laravel\framework\src\Illuminate\Container\Container.php:681
Stack trace:
#0 D:\XAMPP\htdocs\test\vendor\laravel\framework\src\Illuminate\Container\Container.php(681): ReflectionClass->__construct('GrahamCampbell\\...')
#1 D:\XAMPP\htdocs\test\vendor\laravel\framework\src\Illuminate\Container\Container.php(565): Illuminate\Container\Container->build('GrahamCampbell\\...')
#2 D:\XAMPP\htdocs\test\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(702): Illuminate\Container\Container->make('GrahamCampbell\\...')
#3 D:\XAMPP\htdocs\test\vendor\laravel\framework\src\Illuminate\Container\Container.php(239): Illuminate\Foundation\Application->make('GrahamCampbell\\...', Array)
#4 D:\XAMPP\htdocs\test\vendor\laravel\framework\src\Illuminate\Container\Container.php(678): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application))
 in D:\XAMPP\htdocs\test\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 681
PHP Fatal error:  Uncaught ReflectionException: Class GrahamCampbell\Exceptions\NewExceptionHandler does not exist in D:\XAMPP\htdocs\test\vendor\laravel\framework\src\Illuminate\Container\Container.php:681
Stack trace:
#0 D:\XAMPP\htdocs\test\vendor\laravel\framework\src\Illuminate\Container\Container.php(681): ReflectionClass->__construct('GrahamCampbell\\...')
#1 D:\XAMPP\htdocs\test\vendor\laravel\framework\src\Illuminate\Container\Container.php(565): Illuminate\Container\Container->build('GrahamCampbell\\...')
#2 D:\XAMPP\htdocs\test\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(702): Illuminate\Container\Container->make('GrahamCampbell\\...')
#3 D:\XAMPP\htdocs\test\vendor\laravel\framework\src\Illuminate\Container\Container.php(239): Illuminate\Foundation\Application->make('GrahamCampbell\\...', Array)
#4 D:\XAMPP\htdocs\test\vendor\laravel\framework\src\Illuminate\Container\Container.php(678): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application))
 in D:\XAMPP\htdocs\test\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 681
Script php artisan optimize handling the post-update-cmd event returned with error code 255

Removal failed, reverting ./composer.json to its original content.
```

Laravel 5.4 version

How to reproduce:

- laravel new test
- composer require graham-campbell/exceptions
- composer require filp/whoops --dev
- Add `GrahamCampbell\Exceptions\ExceptionsServiceProvider` in providers key
- Replace `App\Exceptions\Handler` with `GrahamCampbell\Exceptions\NewExceptionHandler`
- composer remove filp/whoops
- composer remove graham-campbell/exceptions

**Comment by GrahamCampbell** [comment]
Just run with `--no-scripts`.

**Comment by PixellUp** [comment]
The package has no issue, i just have to replace back to `App\Exceptions\Handler` and remove from providers key :clap:
