### ISSUE TITLE
Error Publishing

### ISSUE THREAD

**Issue by mikeerickson** [GrahamCampbell/Laravel-Exceptions#106]
Hey Graham

When I execute the `vendor:publish` command (this is on a brand new app) I receive the following?  Is the publish actually required (assuming I dont need to configure anything let).   I can easily copy the file over, just wanted to let you know.

```
~/documents/code/laravel/l5-exception-test
❯ php artisan vendor:publish
PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Support\ServiceProvider in /Users/merickson/Documents/code/laravel/l5-exception-test/vendor/laravel/framework/src/Illuminate/Container/Container.php:888
Stack trace:
#0 /Users/merickson/Documents/code/laravel/l5-exception-test/vendor/laravel/framework/src/Illuminate/Container/Container.php(826): Illuminate\Container\Container->unresolvablePrimitive(Object(ReflectionParameter))
#1 /Users/merickson/Documents/code/laravel/l5-exception-test/vendor/laravel/framework/src/Illuminate/Container/Container.php(779): Illuminate\Container\Container->resolvePrimitive(Object(ReflectionParameter))
#2 /Users/merickson/Documents/code/laravel/l5-exception-test/vendor/laravel/framework/src/Illuminate/Container/Container.php(746): Illuminate\Container\Container->resolveDependencies(Array)
#3 /Users/merickson/Documents/code/laravel/l5-exception-test/vendor/laravel/framework/sr in /Users/merickson/Documents/code/laravel/l5-exception-test/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 888
PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Support\ServiceProvider in /Users/merickson/Documents/code/laravel/l5-exception-test/vendor/laravel/framework/src/Illuminate/Container/Container.php:888
Stack trace:
#0 /Users/merickson/Documents/code/laravel/l5-exception-test/vendor/laravel/framework/src/Illuminate/Container/Container.php(826): Illuminate\Container\Container->unresolvablePrimitive(Object(ReflectionParameter))
#1 /Users/merickson/Documents/code/laravel/l5-exception-test/vendor/laravel/framework/src/Illuminate/Container/Container.php(779): Illuminate\Container\Container->resolvePrimitive(Object(ReflectionParameter))
#2 /Users/merickson/Documents/code/laravel/l5-exception-test/vendor/laravel/framework/src/Illuminate/Container/Container.php(746): Illuminate\Container\Container->resolveDependencies(Array)
#3 /Users/merickson/Documents/code/laravel/l5-exception-test/vendor/laravel/framework/sr in /Users/merickson/Documents/code/laravel/l5-exception-test/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 888
```

**Comment by mikeerickson** [comment]
@GrahamCampbell I cured the issue.

Turns out, I also had issues serving `artisan serve` so I debugged closer

Had to use as

```
use GrahamCampbell\Exceptions\NewExceptionHandler as ExceptionHandler;

class Handler extends ExceptionHandler
```

The `as ExceptionHandler` was my doing, but had to provide the use statement
