### ISSUE TITLE
PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [GrahamCampbell\Exceptions\Identifier\IdentifierInterface] is not instantiable.

### ISSUE THREAD

**Issue by Anisi** [GrahamCampbell/Laravel-Exceptions#145]
Hello
I'm using php 7.4 and laravel 7
Lately `composer dump-autoload` raises this exception.
```
PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [GrahamCampbell\Exceptions\Identifier\IdentifierInterface] is not instantiable. in /home/root/public_html/firebase/vendor/laravel/framework/src/Illuminate/Container/Container.php:1013
Stack trace:
#0 /home/root/public_html/firebase/vendor/laravel/framework/src/Illuminate/Container/Container.php(814): Illuminate\Container\Container->notInstantiable()
#1 /home/root/public_html/firebase/vendor/laravel/framework/src/Illuminate/Container/Container.php(687): Illuminate\Container\Container->build()
#2 /home/root/public_html/firebase/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\Container\Container->resolve()
#3 /home/root/public_html/firebase/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Foundation\Application->resolve()
#4 /home/root/public_html/firebase/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\Container\Container->make()
#5 /h in /home/root/public_html/firebase/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 1013
```

**Comment by GrahamCampbell** [comment]
This happens if you have not registered the service provider.

**Comment by Anisi** [comment]
Auto discovery is enabled but I also registered service provider in app.php:
```
GrahamCampbell\Exceptions\ExceptionsServiceProvider::class
```
But problem still remains.

**Comment by kcan** [comment]
I was using `"graham-campbell/exceptions": "^15.1",` and it is registered with the service provider under `config/app.php` -> `providers` using `GrahamCampbell\Exceptions\ExceptionsServiceProvider::class,`. However I still get the error:
```
In Container.php line 1017:

  Target [GrahamCampbell\Exceptions\Identifier\IdentifierInterface] is not instantiable.
```
Do you know why it happens?
