### ISSUE TITLE
Target [GrahamCampbell\Exceptions\Identifier\IdentifierInterface] is not instantiable.

### ISSUE THREAD

**Issue by kcan** [GrahamCampbell/Laravel-Exceptions#157]
**PHP version**:  (hint: `php --version`)
```
PHP 7.4.24 (cli) (built: Sep 23 2021 21:24:59) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.24, Copyright (c), by Zend Technologies
```

**Description**

I was using `"graham-campbell/exceptions": "^15.1"`, and it is registered with the service provider under `config/app.php` -> `providers` using `GrahamCampbell\Exceptions\ExceptionsServiceProvider::class`,. However I still get the error:
```
In Container.php line 1017:

  Target [GrahamCampbell\Exceptions\Identifier\IdentifierInterface] is not instantiable.

```

I tried to add:
```
    "extra": {
        "laravel": {
            "providers": [
                "GrahamCampbell\\Exceptions\\ExceptionsServiceProvider"
            ]
        }
    },
```
still it throws same error. 
The laravel version I used is `^7.0`.

Do you know why it happens?

**How to reproduce**

If I use laravel `^6.0` with `"graham-campbell/exceptions": "^12.1"`. Everything is fine with the code. 

**Possible Solution**

**Additional context**

**Comment by kcan** [comment]
btw, I have the same problem with `php 7.4` and laravel 8 using `"graham-campbell/exceptions": "^15.1"`

**Comment by kcan** [comment]
After I added :
`$app->singleton(GrahamCampbell\Exceptions\Identifier\IdentifierInterface::class, GrahamCampbell\Exceptions\Identifier\HashingIdentifier::class);` to `bootstap/app.php` after the line: 
`$app->singleton(Illuminate\Contracts\Debug\ExceptionHandler::class, GrahamCampbell\Exceptions\ExceptionHandler::class);`

the problem solved. 

But this is really strange solution as the registration should be done with https://github.com/GrahamCampbell/Laravel-Exceptions/blob/15.1/src/ExceptionsServiceProvider.php#L76

Maybe someone can explain here?

**Comment by GrahamCampbell** [comment]
The issue is probably that you didn't add this package high enough up in the list of service providers, and your app is crashing before this service provider is loaded.

**Comment by GrahamCampbell** [comment]
TBH, I kinda feel like this is a usability issue on our side that we should fix. I'll have a think about how to do this.

**Comment by kcan** [comment]
Thank you for reply. I tried to add this service to top of service providers, but it did not help. 

Would be nice to be fixed on your side, thank you.

**Comment by GrahamCampbell** [comment]
It would be helpful to know what in your app is crashing, causing it to load this code so early.

**Comment by GrahamCampbell** [comment]
Can you install xdebug and show me the whole stacktrace?

**Comment by kcan** [comment]
Unfortunatelly I cannot reproduce, I am currently on laravel-8 and I tried to remove the line `$app->singleton(GrahamCampbell\Exceptions\Identifier\IdentifierInterface::class, GrahamCampbell\Exceptions\Identifier\HashingIdentifier::class);` from `bootstap/app.php `, and no errors happening. Strange. 

If I remember correctly, I had the log:
```
2021-11-24 14:09:38,582 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

2021-11-24 14:09:38,583 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

2021-11-24 14:09:38,583 INFO success: queue-worker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

Then the queue-worker suddenly existed, causing the docker container to be stopped. While on the console log there is repeatedly the error:

```
In Container.php line 1017:

 Target [GrahamCampbell\Exceptions\Identifier\IdentifierInterface] is not instantiable.
```

**Comment by GrahamCampbell** [comment]
That's not enough information. I need the entire stack trace from the console log. Can you install xdebug to show it.

**Comment by kcan** [comment]
Hi , I managed to get the stack trace now:
```

Attempting to connect to database ...


Table sessions exists! ...

PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [GrahamCampbell\Exceptions\Identifier\IdentifierInterface] is not instantiable. in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:1093

Stack trace:

#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(886): Illuminate\Container\Container->notInstantiable()

#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\Container\Container->build()

#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): Illuminate\Container\Container->resolve()

#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\Foundation\Application->resolve()

#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(836): Illuminate\Container\Container->make()

#5 /var/www/html/vendor/graham-campbell/exceptions/src/ExceptionHandler.php(93): Illuminate\Foundation\Applicatio in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 1093
```

Where do you think the problem is? 

Thanks

**Comment by GrahamCampbell** [comment]
I need to see more lines of the stacktrace, and possibly the previous error.

**Comment by kcan** [comment]
Hi, could you help to advice how to get more lines,  the above is all i can get from stdout of the container. do i need to set extra debug level somewhere?

If you talk about previous error, i do not see any also from stdout.

**Comment by kcan** [comment]
As i also noticed, the error happens, when i update config of laravel under the config folder. once i added:
```
$app->singleton(GrahamCampbell\Exceptions\Identifier\IdentifierInterface::class, GrahamCampbell\Exceptions\Identifier\HashingIdentifier::class); 
```
to `bootstap/app.php`
the error disapears. 
Then i can remove the above line. And the container start without an issue. But if there is new change in the config, the error appears again.
