### ISSUE TITLE
Getting error after install

### ISSUE THREAD

**Issue by francocorreasosa** [GrahamCampbell/Laravel-Exceptions#60]
I'm getting this after tried to install `GrahamCampbell/Laravel-Exceptions` package. 
I already removed it and did `composer install` again but it's still the same.

Laravel 5.2

```
  [RuntimeException]
  Error Output: PHP Fatal error:  Uncaught ReflectionException: Class log does not exist in /Users/franco/Code/sendit/vendor/laravel/framework/src/Illuminate/Container/Container.php:738
  Stack trace:
  #0 /Users/franco/Code/sendit/vendor/laravel/framework/src/Illuminate/Container/Container.php(738): ReflectionClass->__construct('log')
  #1 /Users/franco/Code/sendit/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build('log', Array)
  #2 /Users/franco/Code/sendit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('log', Array)
  #3 /Users/franco/Code/sendit/vendor/laravel/framework/src/Illuminate/Container/Container.php(853): Illuminate\Foundation\Application->make('log')
  #4 /Users/franco/Code/sendit/vendor/laravel/framework/src/Illuminate/Container/Container.php(808): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
  #5 /Users/franco/Code/sendit/vendor/laravel/framework/src/Illuminate/Container/Container.php(777): Il in /Users/franco/Code/sendit/vendor/laravel/framework/src/Illuminate/Container/Container
  .php on line 738

```

**Comment by vinkla** [comment]
Makes sure your application can read the config directory and check if there are any custom function calls within your configuration files.

**Comment by GrahamCampbell** [comment]
This error is indicating it's crashing early on. Did you add the service provider. What does your exception handler look like?
